print('====== DESAFIO 2 ======')
print('Qual a sua data de nascimento? ')
dia = input('DIA: ')
mes = input('MÊS: ')
ano = input('ANO: ')
print('Você nasceu no dia',dia,'de',mes,'de',ano,'. Correto?')
